name: Run Tests

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PET
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .
    - name: Run tests
      run: |
        cd tests && pytest .